env:
  browser: true
  es2021: true
extends: 'airbnb'
parser: "babel-eslint"
parserOptions:
  ecmaVersion: 2020
  sourceType: module
rules: {
  "linebreak-style": 0,
  "import/extensions": "off",
  "strict": "off",
  "max-len": "warn",
  "class-methods-use-this": "off",
  "no-undef": "off",
  "no-unused-vars": "off",
  "no-param-reassign": "off",
  "no-multi-assign": "off",
  "no-return-assign": "off",
  "no-cond-assign": "off",
  "func-names": "off",
  "consistent-return": "off",
  "no-restricted-globals": "off",
  "no-irregular-whitespace": "off",
  "no-useless-constructor": "off",
  "max-classes-per-file": "off",
  "import/prefer-default-export": "off",
  "import/no-unresolved": "off"
}
